name: Deploy to prod

on:
  workflow_run:
    workflows: [Build for prod]
    types: [completed]
    branches: [feat/add-ci-cd]

jobs:
  deploy_prod:
    name: Deploy to production
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: self-hosted

    steps:
    - run: echo "Hello from deploy job!"
