name: Test

on:
  workflow_run:
    workflows: [Lint]
    types: [completed]
    # branches: [feat/add-ci-cd]

jobs:
  test-backend:
    name: Test backend
    if: |
      github.event.workflow_run.conclusion == 'success' ||
      github.event.workflow_run.conclusion == 'failure'
    runs-on: self-hosted

    steps:
    - run: echo "Hello from test job!"
